################################################################
#                                                              #
#         Playbook Ansible - Configuração Cloudera 5           #
#         Criado por: Anselmo Borges                           #
#         Data de criação: 14.10.2018                          #
#         Ultima atualização: 14.10.2018                       #
#                                                              #
################################################################                                    

- name: "Playbook de instalação Cloudera 5"
  hosts: clusterzao
  tasks:

    - name: "Atualizando todos os repositórios do YUM"
      yum: 
        name: "*"
        state: latest
      become: true
      become_method: sudo
      become_user: root

    - name: Instala pre-reqs via YUM
      yum: name={{ item }} 
      state: latest
      with_items:
        - wget
        - telnet
        - ntp
        - mariadb-server
        - dstat
        - nscd
        - firewalld
      become: yes
      become_method: sudo
      become_user: root

    - name: "Movimentando Hosts"
      copy:
        src: confs/hosts
        dest: /etc/
        owner: root
        group: root
        mode: 0644   
      become: yes
      become_method: sudo
      become_user: root

    - name: "Parando o Firewall"
      service: 
        name: firewalld
        state: stopped 
      become: yes
      become_method: sudo
      become_user: root

    - name: "Desabilitando o Firewall"
      service: 
        name: firewalld
        enabled: no
      become: yes
      become_method: sudo
      become_user: root


